version: '3.4'

services:
  redis:
    image: 'redis:alpine'
  fcprojectbot:
    depends_on: [ redis ]
    image: ghcr.io/dongle-the-gadget/projectsbot:master
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PROJECTS_REDIS_HOST=redis
      - PROJECTS_REDIS_PORT=6379
    env_file:
      - .env
  watchtower:
    image: containrrr/watchtower
    volumes:
      -/var/run/docker.sock:/var/run/docker.sock