version: '3.4'

services:
  redis:
    image: 'redis:alpine'
  fcprojectbot:
    depends_on: [ redis ]
    image: ghcr.io/dongle-the-gadget/projectsbot:master
    build:
      context: .
      dockerfile: Dockerfile
  watchtower:
    image: containrrr/watchtower
    volumes:
      -/var/run/docker.sock:/var/run/docker.sock